customhost = "database-1.cqezgwk8aajx.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "sityiesian-employee"
customregion = "us-east-1"
